### ISSUE TITLE
Sunbed on 47's bedroom balcony has the wrong sitting animation

### ISSUE THREAD

**Issue by dribbleondo** [glacier-modding/H3-Unofficial-Community-Patch#226]
He should be laying down on it, like he does in Bangkok or in the sunbed on the bottom floor.

Changed the entity to remove the original sunbed and replaced it with the entity instead:
![screenshot_8110](https://github.com/user-attachments/assets/e93abee3-95aa-47d4-b6d7-e8f90bacd91c)

(also to anyone wondering, 47 really _does_ sit that far to the right on the sunbed, that's not a bug specific to this mod).

**Comment by Ocean-Minnow** [comment]
He seems to be laying on it in that image. Is that not the right animation?

**Comment by dribbleondo** [comment]
He sits down as if he's on a normal chair in vanilla:
![screenshot_8135](https://github.com/user-attachments/assets/a533c851-9ff6-46e8-b964-78135dc6eb45)

**Comment by Ocean-Minnow** [comment]
Closing alongside #227 since I'm convinced this was intentional - if you still think it isn't please let me know and I'll reopen.
