### ISSUE TITLE
47 can die at The Splitter shooting range when he should be standing safely out of range

### ISSUE THREAD

**Issue by VoodooHillbilly** [glacier-modding/H3-Unofficial-Community-Patch#263]
The kill box for the clones' shooting range extends well beyond the firing line. This can cause 47 to die when he appears to be standing safely out of the line of fire.
![shooting range before](https://github.com/user-attachments/assets/5077d6a9-e62a-44b9-a3d9-99d88beaec3e)

**Comment by dribbleondo** [comment]
This needs to be moved to Officially Fixed on the board.
