### ISSUE TITLE
Paris security guard belt items clipping

### ISSUE THREAD

**Issue by Jax765** [glacier-modding/H3-Unofficial-Community-Patch#275]
The items on the guard's belt have very wonky physics, causing them to wobble all over the place and clip into each other.
![1659040_20241226185531_1](https://github.com/user-attachments/assets/61150ebf-91cf-4760-bef4-c8e35f87e0a0)

**Comment by Ocean-Minnow** [comment]
This can't be fixed with the currently available tools, since they break cloth physics (which this most likely uses)
