### ISSUE TITLE
Firing a pistol while holding a briefcase produces the old recoil animation from the prior games

### ISSUE THREAD

**Issue by Jax765** [glacier-modding/H3-Unofficial-Community-Patch#296]
In H2016 and H2, the recoil on the firing animation was quite exaggerated. In H3, IO toned it down a bit. However, it reverts back to the old animation if you shoot while holding a briefcase.

**Comment by AnthonyFuller** [comment]
Not possible to fix. We do not have animation tooling.

**Comment by Ocean-Minnow** [comment]
Hopefully that changes eventually, but for now I'll close the issue.

**Comment by atampy25** [comment]
Shouldn't this be closed as "not planned" rather than completed
