### ISSUE TITLE
Dumpster in Chongqing has French language text

### ISSUE THREAD

**Issue by Ocean-Minnow** [glacier-modding/H3-Unofficial-Community-Patch#79]
A dumpster in Chongqing (under the stairs to the rooftop, near the walkway start) has French text mentioning Paris, although a textless version of this dumpster exists.

This dumpster uses `setpiece_container_body_plasticdumpster_paris` when it should use `setpiece_container_body_plasticdumpster_paris_notext`

It's also possible that the Paris dumpster was intended as a placeholder, and was meant to use `setpiece_container_body_metaldumpster_rat` which visually fits the area nicely.

A picture of the dumpster is below, provided by Joris on Discord

![image](https://github.com/glacier-modding/H3-Community-Patches/assets/152698454/580e80d7-7a10-4733-bb82-48e5773b3595)

**Comment by dribbleondo** [comment]
This is a similar problem to the GAMA towel racks in Santa Fortuna.

Welcome to IOI's reused asset emporium!

**Comment by Ocean-Minnow** [comment]
Is there a version of the towel racks with no text as well?
